#!/usr/bin/env python3
# Generate port_n64/n64_song_offsets.inc: a songId -> ROM byte-offset table for
# the N64 M4A synth (Option 2). The offset is where each song's SongHeader lives
# in the cart baserom = sounds.json `start` + `options.headerOffset`, keyed by
# the song label. We emit designated initializers ([BGM_TITLE_SCREEN] = N,) so
# the C compiler resolves the songId index from sound.h's enum — no enum-value
# duplication here. Regenerate when assets/sounds.json changes.
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
TMC = os.path.normpath(os.path.join(ROOT, "..", "tmc"))
SOUNDS = os.path.join(TMC, "assets", "sounds.json")
LABELS = os.path.join(TMC, "port", "port_song_midi_table.inc")
OUT = os.path.join(ROOT, "n64_song_offsets.inc")


def main():
    # label -> SongHeader ROM byte offset (start + headerOffset), USA flat list.
    label_off = {}
    for e in json.load(open(SOUNDS)):
        path = e.get("path", "")
        if not path.startswith("sounds/") or not path.endswith(".bin"):
            continue
        label = path[len("sounds/"):-len(".bin")]
        start = e.get("start")
        hoff = e.get("options", {}).get("headerOffset")
        if start is None or hoff is None:
            continue
        label_off[label] = int(start) + int(hoff)

    # [DESIGNATOR] = "label",  ->  designator -> label
    rx = re.compile(r'\[(\w+)\]\s*=\s*"([^"]+)"')
    lines = []
    matched = 0
    for designator, label in rx.findall(open(LABELS).read()):
        off = label_off.get(label)
        if off is None:
            continue
        lines.append(f"    [{designator}] = {off}u,")
        matched += 1

    with open(OUT, "w") as f:
        f.write("/* GENERATED by port_n64/gen_song_offsets.py — DO NOT HAND-EDIT.\n")
        f.write(" * songId -> cart ROM byte offset of the song's SongHeader. */\n")
        f.write("\n".join(lines))
        f.write("\n")
    print(f"[gen_song_offsets] {matched} songs -> {os.path.relpath(OUT, ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
